import type { Metadata } from "next";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import { Geist, Geist_Mono } from "next/font/google";
import * as Sentry from "@sentry/nextjs";
import { GA_MEASUREMENT_ID, hasGaMeasurementId } from "@/lib/analytics";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    ...Sentry.getTraceData(),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {hasGaMeasurementId ? (
          <>
            <GoogleAnalytics gaId={GA_MEASUREMENT_ID} />
            <GoogleTagManager gtmId={GA_MEASUREMENT_ID} />
          </>
        ) : null}
        {children}
      </body>
    </html>
  );
}
